# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 236ba4882e83cfc7a7feec54f20492a4bf7a58cdc3df45368f275fea7a3fefc98baac7cea018f405830f833b98414f699ef36db3a07daaa197e6066a61842507

test:
  secret_key_base: 857959ca09be31b70aa0ed6e688dfd49b8baaa9701096307198efd1b135557c590585e82cc80d0ad45ee164326e185477e8cdb06108274d60cc462e941002100

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sendgrid_username: <%= ENV["SENDGRID_USERNAME"] %>
  sendgrid_password: <%= ENV["SENDGRID_PASSWORD"] %>
